# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "NotchBar"
edition = "2024"

# The `_lib` suffix is necessary to prevent conflict with the bin name.
# Issue only on Windows? https://github.com/rust-lang/cargo/issues/8519
[lib]
name = "notchbar_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
