name: Release
run-name: ${{ github.actor }} is running release actions.
on:
    push:
        branches:
            - Release-Action
    workflow_dispatch:
    release:
        types: [published]
jobs:
    Release-Actions:
        runs-on: ubuntu-latest
        steps:
            - run: echo "github.event_name = ${{ github.event_name }}"
            - run: echo "runner.os = ${{ runner.os }}"
            - run: echo "github.ref = ${{ github.ref }}"
            - run: echo "github.repository = ${{ github.repository }}"

            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                  sparse-checkout: |
                      README.md
                  sparse-checkout-cone-mode: false

            - name: List files in the repository
              run: |
                  echo "github.workspace = ${{ github.workspace }}"
                  ls ${{ github.workspace }}
            
            - name: Get Latest Release Download URL
              id: latest-release-download-url
              run: |
                  # echo "LATEST_RELEASE_DOWNLOAD_URL=$(jq -r 'max_by(.created_at) | .assets | map(select(.name == "NotchBar.app.zip")) | max_by(.created_at) | .browser_download_url' <<< $(curl --silent https://api.github.com/repos/navtoj/notchbar/releases))" >> "$GITHUB_OUTPUT"
                  
                  # Fetch Repository Releases
                  releases=$(curl --silent https://api.github.com/repos/navtoj/notchbar/releases)

                  # Extract Download URL
                  browser_download_url=$(jq -r '

                    # get latest release
                    max_by(.created_at)
                  
                    # filter asset files
                    | .assets
                    | map(select(.name == "NotchBar.app.zip"))
                  
                    # get latest asset
                    | max_by(.created_at)

                    # get download url
                    | .browser_download_url

                  ' <<< "$releases")

                  # Save URL to GitHub Actions Output
                  echo "LATEST_RELEASE_DOWNLOAD_URL=$browser_download_url" >> "$GITHUB_OUTPUT"

            - name: Debug
              run: echo "The download url is ${{ steps.latest-release-download-url.outputs.LATEST_RELEASE_DOWNLOAD_URL }}"

            - run: echo "job.status = ${{ job.status }}"
