name: Release
on:
    push:
        branches:
            - Release-Action
    workflow_dispatch:
    release:
        types: [published]
jobs:
    Release-Actions:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                  sparse-checkout: |
                      README.md
                  sparse-checkout-cone-mode: false

            - name: List files in the repository
              run: |
                  echo "github.workspace = ${{ github.workspace }}"
                  ls ${{ github.workspace }}
            
            - name: Get Latest Release Download URL
              id: latest-release-download-url
              run: |                  
                  # Fetch Repository Releases
                  releases=$(curl --silent https://api.github.com/repos/navtoj/notchbar/releases)

                  # Extract Download URL
                  browser_download_url=$(jq -r '

                    # get latest release
                    max_by(.created_at)
                  
                    # filter asset files
                    | .assets
                    | map(select(.name == "NotchBar.app.zip"))
                  
                    # get latest asset
                    | max_by(.created_at)

                    # get download url
                    | .browser_download_url

                  ' <<< "$releases")

                  # Save URL to Step Output
                  echo "value=$browser_download_url" >> "$GITHUB_OUTPUT"

            - name: Debug
              run: |
                echo "The download url is ${{ steps.latest-release-download-url.outputs.value }}"

            - name: Update README.md
              run: |
                sed -i "s|https://[^ ]*NotchBar\.app\.zip|h${{ steps.latest-release-download-url.outputs.value }}p|g" README.md
                cat README.md

            - run: echo "job.status = ${{ job.status }}"
